### PR TITLE
Add libhoudini.so from Android 7 x86 for PC

### PR DESCRIPTION
**Pull request by umerov1999**

### CODE REVIEW

**Comment by Flex1911** [comment]
Single libhoudini.so? Do not think that it will be enough.

**Comment by umerov1999** [comment]
http://4pda.ru/forum/index.php?showtopic=128559&st=12800#entry53051787

**Comment by umerov1999** [comment]
android x86_x64 7.1 for pc https://yadi.sk/d/xg2LRaNfz55nK

**Comment by Flex1911** [comment]
Just tested it. There is fugu's binaries in that android x86 build. 
We have x86 CPU, but houdini expects x86_64. It doesn't work just like 6.0 fugu's blobs:
```
01-10 18:52:42.481  3274  3274 D houdini : [3274] Initialize library(version: 7.0.0_y.48671 RELEASE)... successfully.
01-10 18:52:43.334  3274  3274 D houdini : [3274] Expected CPU feature >> AES << is not supported.
01-10 18:52:43.334  3274  3274 D houdini : [3274] Expected CPU feature >> SSE4_2 << is not supported.
01-10 18:52:43.334  3274  3274 D houdini : [3274] Expected CPU feature >> SSE4_1 << is not supported.
01-10 18:52:43.334  3274  3274 D houdini : [3274] Expected CPU feature >> SSE3 << is not supported.
01-10 18:52:43.334  3274  3274 D houdini : [3274] Expected CPU feature >> SSE2 << is not supported.
01-10 18:52:43.335  3274  3274 D houdini : [3274] Expected CPU feature >> SSE << is not supported.
01-10 18:52:43.335  3274  3274 D houdini : [3274] Expected CPU feature >> MMX << is not supported.
01-10 18:52:43.335  3274  3274 D houdini : [3274] Expected CPU feature >> CMOV << is not supported.
```

I think that we should wait for official android x86 builds, they should include updated houdini blobs for x86 platform.

**Comment by umerov1999** [comment]
http://geektillithertz.com/wordpress/index.php/2016/09/02/android-x86-nougat/

**Pull request closed without merging**
